baseurl             = "https://endbaddesign.com/" # Must end with /
languageCode        = "en-us"
title               = "End Bad Design"
theme               = "introduction"
enforce_ssl         = "your-url.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "xxx" # Enable Disqus for comments
googleAnalytics   = "UA-59921108-18"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "End Bad Design" # Full name shows on blog post pages
firstname     = "Anthony" # First name shows in introduction on main page
tagline       = "Let's End Bad Design" # Appears after the introduction
introheight   = "large" # Input either 'medium' or 'large' or 'fullheight'
theme         = "light" # Choose 'light' or 'dark'
avatar        = "img/profile.png" # Path to image in static folder eg. img/avatar.png
email         = "EndBadDesign@gmail.com" # Shows in contact section, or leave blank to omit
localtime     = false # Show your current local time in contact section
timezone      = "America/Chicago" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 CST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Helping churches end bad design one blog post at a time."
faviconfile   = "img/favnew.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "©2017 End Bad Design. All rights reserved." # Text to show in footer (overrides default text)
fadein        = true # Turn on/off the fade-in effect

showblog        = true # Show Blog section on home page
showallposts    = true # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = false # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/project1.jpg"
project1title   = "Project 1"

project2link    = "#"
project2img     = "img/project2.jpg"
project2title   = "Project 2"

project3link    = "#"
project3img     = "img/project3.jpg"
project3title   = "Project 3"


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
url = "https://twitter.com/aroberts1228"
icon = "twitter"

[[params.social]]
url = "https://facebook.com/rocketpunchlabs"
icon = "facebook"

[[params.social]]
url = "https://instagram.com/rocketpunchlabs"
icon = "instagram"
